# Netlify is no longer being used by the project.
# However, I am keeping this here in case others want to host their own instance via Netlify :)
[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[headers]]
    for = "/*"
    [headers.values]
        X-Frame-Options = "DENY"
        X-XSS-Protection = "1; mode=block"
        X-Content-Type-Options = "nosniff"